"""initial schema

Revision ID: 991d504abdac
Revises: 
Created: 2026-08-21 13:48:39.988581
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '991d504abdac'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('organization_members',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='org_role'), server_default='member', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_organization_members_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'user_id', name=op.f('pk_organization_members'))
    )
    op.create_index('idx_org_members_user', 'organization_members', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_projects_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('org_id', 'slug', name='uq_projects_org_slug')
    )
    op.create_index('idx_projects_org', 'projects', ['org_id'], unique=False)
    op.create_table('retry_policies',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.Enum('fixed', 'linear', 'exponential', name='retry_strategy'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('base_delay_ms', sa.Integer(), server_default=sa.text('1000'), nullable=False),
    sa.Column('max_delay_ms', sa.Integer(), server_default=sa.text('3600000'), nullable=False),
    sa.Column('jitter', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_delay_ms >= 0', name=op.f('ck_retry_policies_base_delay_non_negative')),
    sa.CheckConstraint('max_attempts >= 1', name=op.f('ck_retry_policies_max_attempts_positive')),
    sa.CheckConstraint('max_delay_ms >= base_delay_ms', name=op.f('ck_retry_policies_max_delay_gte_base')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_retry_policies_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retry_policies')),
    sa.UniqueConstraint('project_id', 'name', name='uq_retry_policies_project_name')
    )
    op.create_table('workers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('queue_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('starting', 'active', 'draining', 'dead', 'stopped', name='worker_status'), server_default='starting', nullable=False),
    sa.Column('jobs_processed', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('concurrency >= 1', name=op.f('ck_workers_concurrency_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workers_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers'))
    )
    op.create_index('idx_workers_alive', 'workers', ['last_heartbeat_at'], unique=False, postgresql_where=sa.text("status IN ('active', 'draining')"))
    op.create_index('idx_workers_project', 'workers', ['project_id'], unique=False)
    op.create_table('queues',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('is_paused', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('visibility_timeout_s', sa.Integer(), server_default=sa.text('300'), nullable=False),
    sa.Column('default_timeout_s', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('rate_limit_per_sec', sa.Integer(), nullable=True),
    sa.Column('retry_policy_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_concurrency >= 1', name=op.f('ck_queues_max_concurrency_positive')),
    sa.CheckConstraint('visibility_timeout_s > 0', name=op.f('ck_queues_visibility_timeout_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_queues_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_policy_id'], ['retry_policies.id'], name=op.f('fk_queues_retry_policy_id_retry_policies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queues')),
    sa.UniqueConstraint('project_id', 'name', name='uq_queues_project_name')
    )
    op.create_index('idx_queues_project', 'queues', ['project_id'], unique=False)
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('beat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active_jobs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('jobs_processed', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cpu_percent', sa.Integer(), nullable=True),
    sa.Column('memory_mb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_worker_heartbeats_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_heartbeats'))
    )
    op.create_index('idx_hb_worker', 'worker_heartbeats', ['worker_id', sa.literal_column('beat_at DESC')], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_scheduled_jobs_queue_id_queues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_jobs')),
    sa.UniqueConstraint('queue_id', 'name', name='uq_scheduled_jobs_queue_name')
    )
    op.create_index('idx_sched_due', 'scheduled_jobs', ['next_run_at'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('queued', 'scheduled', 'claimed', 'running', 'completed', 'failed', 'dead', 'cancelled', name='job_status'), server_default='queued', nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('timeout_s', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.Uuid(), nullable=True),
    sa.Column('lock_token', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_job_id', sa.Uuid(), nullable=True),
    sa.Column('depends_on', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt >= 0', name=op.f('ck_jobs_attempt_non_negative')),
    sa.CheckConstraint('max_attempts >= 1', name=op.f('ck_jobs_max_attempts_positive')),
    sa.CheckConstraint('timeout_s > 0', name=op.f('ck_jobs_timeout_positive')),
    sa.ForeignKeyConstraint(['claimed_by'], ['workers.id'], name=op.f('fk_jobs_claimed_by_workers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_jobs_queue_id_queues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_job_id'], ['scheduled_jobs.id'], name=op.f('fk_jobs_scheduled_job_id_scheduled_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('idx_jobs_batch', 'jobs', ['batch_id'], unique=False, postgresql_where=sa.text('batch_id IS NOT NULL'))
    op.create_index('idx_jobs_claim', 'jobs', ['queue_id', sa.literal_column('priority DESC'), sa.literal_column('run_at ASC')], unique=False, postgresql_where=sa.text("status IN ('queued', 'scheduled')"))
    op.create_index('idx_jobs_explorer', 'jobs', ['queue_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_jobs_idempotency', 'jobs', ['queue_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index('idx_jobs_reaper', 'jobs', ['claimed_at'], unique=False, postgresql_where=sa.text("status IN ('claimed', 'running')"))
    op.create_index('idx_jobs_scheduled_parent', 'jobs', ['scheduled_job_id'], unique=False)
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('original_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('died_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replayed_job_id', sa.Uuid(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_dead_letter_queue_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_dead_letter_queue_queue_id_queues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replayed_job_id'], ['jobs.id'], name=op.f('fk_dead_letter_queue_replayed_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letter_queue'))
    )
    op.create_index('idx_dlq_job', 'dead_letter_queue', ['job_id'], unique=False)
    op.create_index('idx_dlq_queue', 'dead_letter_queue', ['queue_id', sa.literal_column('died_at DESC')], unique=False)
    op.create_index('idx_dlq_unreplayed', 'dead_letter_queue', [sa.literal_column('died_at DESC')], unique=False, postgresql_where=sa.text('replayed_at IS NULL'))
    op.create_table('job_executions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('succeeded', 'failed', 'timeout', 'lost', name='execution_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_executions_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_job_executions_worker_id_workers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_executions')),
    sa.UniqueConstraint('job_id', 'attempt_number', name='uq_executions_job_attempt')
    )
    op.create_index('idx_exec_job', 'job_executions', ['job_id', sa.literal_column('attempt_number DESC')], unique=False)
    op.create_index('idx_exec_metrics', 'job_executions', [sa.literal_column('started_at DESC'), 'status'], unique=False)
    op.create_index('idx_exec_worker', 'job_executions', ['worker_id'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.Enum('debug', 'info', 'warning', 'error', name='log_level'), server_default='info', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['job_executions.id'], name=op.f('fk_job_logs_execution_id_job_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_logs_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_logs'))
    )
    op.create_index('idx_logs_execution', 'job_logs', ['execution_id'], unique=False)
    op.create_index('idx_logs_job', 'job_logs', ['job_id', sa.literal_column('logged_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_logs_job', table_name='job_logs')
    op.drop_index('idx_logs_execution', table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index('idx_exec_worker', table_name='job_executions')
    op.drop_index('idx_exec_metrics', table_name='job_executions')
    op.drop_index('idx_exec_job', table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index('idx_dlq_unreplayed', table_name='dead_letter_queue', postgresql_where=sa.text('replayed_at IS NULL'))
    op.drop_index('idx_dlq_queue', table_name='dead_letter_queue')
    op.drop_index('idx_dlq_job', table_name='dead_letter_queue')
    op.drop_table('dead_letter_queue')
    op.drop_index('idx_jobs_scheduled_parent', table_name='jobs')
    op.drop_index('idx_jobs_reaper', table_name='jobs', postgresql_where=sa.text("status IN ('claimed', 'running')"))
    op.drop_index('idx_jobs_idempotency', table_name='jobs', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('idx_jobs_explorer', table_name='jobs')
    op.drop_index('idx_jobs_claim', table_name='jobs', postgresql_where=sa.text("status IN ('queued', 'scheduled')"))
    op.drop_index('idx_jobs_batch', table_name='jobs', postgresql_where=sa.text('batch_id IS NOT NULL'))
    op.drop_table('jobs')
    op.drop_index('idx_sched_due', table_name='scheduled_jobs', postgresql_where=sa.text('is_active'))
    op.drop_table('scheduled_jobs')
    op.drop_index('idx_hb_worker', table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_index('idx_queues_project', table_name='queues')
    op.drop_table('queues')
    op.drop_index('idx_workers_project', table_name='workers')
    op.drop_index('idx_workers_alive', table_name='workers', postgresql_where=sa.text("status IN ('active', 'draining')"))
    op.drop_table('workers')
    op.drop_table('retry_policies')
    op.drop_index('idx_projects_org', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_org_members_user', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
