"""Declarative base and shared column conventions."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming convention for every constraint and index.
#
# Without this, Alembic autogenerate produces migrations containing unnamed
# constraints, and a later `ALTER TABLE ... DROP CONSTRAINT` has nothing stable
# to reference -- which makes downgrade migrations unreliable. Naming them by
# convention means every constraint has a deterministic, reproducible name.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Root of the declarative hierarchy."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_pk() -> Mapped[uuid.UUID]:
    """Standard UUID primary key, generated by PostgreSQL.

    `gen_random_uuid()` is built into PostgreSQL 13+, so no pgcrypto extension
    is required. Generating server-side rather than in Python means a row
    inserted by any client -- our API, a psql session, a future service in
    another language -- gets a valid key without duplicating the logic.
    """
    return mapped_column(
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )


class TimestampMixin:
    """`created_at` / `updated_at` on every mutable entity.

    Both are server-side: `now()` on insert, and `onupdate` for `updated_at`.
    Using the database clock rather than the application clock matters here
    because API pods, workers, and the scheduler are separate processes whose
    system clocks may drift. Every timestamp in this schema is therefore written
    by PostgreSQL and comparable across services.

    All timestamps are `timestamptz` (UTC). A job scheduler that stores naive
    timestamps breaks the moment a cron entry crosses a DST boundary.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
